channels:
- conda-forge
dependencies:
- python=3.7
- pip:
  - azureml-core==1.27.0
  - azureml-defaults==1.27.0
  - joblib==1.1.0
  - azureml-sdk==1.27.0
  - pillow==9.0.1
  - tensorflow==2.8.0
  - numpy==1.21.5
  - itsdangerous==2.0.1
  - Jinja2==3.0.3
  - protobuf==3.20.0

name: basic_env